---
## Example for Ansible Pull
## by Raymii.org

- name: Ansible Example Pull Mode
  hosts: localhost
  user: root
  connection: local # or ssh or paramiko

  tasks:
    - name: copy main program
      copy: src=files/ips.py dest=/home/pi/main.py
      notify:
      - restart main

    - name: make sure main program running
      supervisorctl: 
        name: main
        state: running 
        supervisorctl_path: /usr/local/bin/supervisorctl

  handlers:
    - name: restart main
      supervisorctl:
        name: main
        state: restarted 
        supervisorctl_path: /usr/local/bin/supervisorctl